// Auto-generated by deploy script — localhost @ 2026-03-31T17:09:06.341Z
export const ADDRESSES = {
  "bidToken": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  "sellToken": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  "auction": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  "demoHelper": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
};

export const NETWORK = "localhost";
export const CHAIN_ID = undefined;
