// Auto-generated by deploy script — sepolia @ 2026-03-31T08:10:13.392Z
export const ADDRESSES = {
  "bidToken": "0x884fd7ea6F8598Df1A87D753Bb291D451AEA6726",
  "sellToken": "0x327044131Ee5668C4975f68E96bA20BF2B14ca57",
  "auction": "0x0F4DAe0DfCCF5Ed79b63Dd662Aa25F3150f5cb75"
};

export const NETWORK = "sepolia";
export const CHAIN_ID = 11155111;
