// Auto-generated by deploy script — sepolia @ 2026-05-10T17:56:01.457Z
export const ADDRESSES = {
  "bidToken": "0x5AfdFE20C822D1dDa434a5E081C828407983BB08",
  "sellToken": "0x7f1d323d5A9590C1c6c28caF4233C4382aa50260",
  "auction": "0xB622C061dc4a4d1637145604ebbaE53a77cF7D36"
};

export const NETWORK = "sepolia";
export const CHAIN_ID = 11155111;
