// Auto-generated by deploy script — sepolia @ 2026-03-27T06:33:12.712Z
export const ADDRESSES = {
  "bidToken": "0xaA14364aDc5A7BCCfd464d608B77b684cb75949C",
  "sellToken": "0xe7E2F0688E4C96C03d49F65A97A69a9C954e75B2",
  "auction": "0xe811BB16011d730FF663349B6fA81041605755F2"
};

export const NETWORK = "sepolia";
export const CHAIN_ID = 11155111;
