import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  const isTestnet = network.name === "sepolia";

  console.log(`Deploying to ${network.name} with account:`, deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)));

  // Deploy bid token
  console.log("\n--- Deploying MockERC20 (BidToken) ---");
  const TokenFactory = await ethers.getContractFactory("MockERC20");
  const bidToken = await TokenFactory.deploy("Confidential USDC", "cUSDC");
  await bidToken.waitForDeployment();
  const bidTokenAddress = await bidToken.getAddress();
  console.log("BidToken deployed:", bidTokenAddress);

  // Deploy sell token
  console.log("\n--- Deploying MockERC20 (SellToken) ---");
  const sellToken = await TokenFactory.deploy("Governance Token", "GOV");
  await sellToken.waitForDeployment();
  const sellTokenAddress = await sellToken.getAddress();
  console.log("SellToken deployed:", sellTokenAddress);

  // Deploy auction contract
  console.log("\n--- Deploying SealedAuction ---");
  const AuctionFactory = await ethers.getContractFactory("SealedAuction");
  const auction = await AuctionFactory.deploy();
  await auction.waitForDeployment();
  const auctionAddress = await auction.getAddress();
  console.log("SealedAuction deployed:", auctionAddress);

  const addresses: Record<string, string> = {
    bidToken: bidTokenAddress,
    sellToken: sellTokenAddress,
    auction: auctionAddress,
  };

  // Only deploy DemoHelper for local hardhat (not needed on testnet — frontend uses client-side encryption)
  if (!isTestnet) {
    console.log("\n--- Deploying DemoHelper ---");
    const HelperFactory = await ethers.getContractFactory("DemoHelper");
    const helper = await HelperFactory.deploy(auctionAddress);
    await helper.waitForDeployment();
    const helperAddress = await helper.getAddress();
    console.log("DemoHelper deployed:", helperAddress);
    addresses.demoHelper = helperAddress;
  } else {
    console.log("\n--- Skipping DemoHelper (testnet uses client-side FHE encryption) ---");
  }

  console.log("\n========================================");
  console.log("Deployment complete");
  console.log("========================================");
  for (const [name, addr] of Object.entries(addresses)) {
    console.log(`${name.padEnd(16)}${addr}`);
  }
  console.log("========================================");

  // Write addresses to frontend
  const frontendDir = path.join(__dirname, "..", "frontend", "src", "contracts");
  const addressesFile = path.join(frontendDir, "addresses.js");
  const content = `// Auto-generated by deploy script — ${network.name} @ ${new Date().toISOString()}
export const ADDRESSES = ${JSON.stringify(addresses, null, 2)};

export const NETWORK = "${network.name}";
export const CHAIN_ID = ${network.config.chainId};
`;
  fs.writeFileSync(addressesFile, content);
  console.log(`\nAddresses written to ${addressesFile}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
