/**
 * VeilBid deploy script
 *
 * Deploys:
 *   - VeilBidUSDC (ERC-7984 confidential bid token, OZ reference impl v0.4.0)
 *   - MockERC20    (sell token — the asset being auctioned, public ERC-20)
 *   - SealedAuction (Vickrey two-pass FHE auction)
 *   - DemoHelper    (local hardhat only — frontend uses client-side FHE)
 *
 * Outputs addresses to frontend/src/contracts/addresses.js.
 *
 * Usage:
 *   npx hardhat run scripts/deploy.ts --network sepolia
 *   npx hardhat run scripts/deploy.ts --network mainnet
 */

import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  const isLocal = network.name === "hardhat" || network.name === "localhost";

  console.log(`Deploying to ${network.name} with account:`, deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  // === Bid token: VeilBidUSDC (ERC-7984) ===
  console.log("--- Deploying VeilBidUSDC (ERC-7984 confidential token) ---");
  const BidFactory = await ethers.getContractFactory("VeilBidUSDC");
  const bidToken = await BidFactory.deploy();
  await bidToken.waitForDeployment();
  const bidTokenAddress = await bidToken.getAddress();
  console.log("VeilBidUSDC deployed:", bidTokenAddress);
  console.log("  - balances are FHE-encrypted (euint64)");
  console.log("  - operator-model approvals (no ERC-20 allowance leak)");

  // === Sell token: standard ERC-20 ===
  console.log("\n--- Deploying MockERC20 (SellToken) ---");
  const SellFactory = await ethers.getContractFactory("MockERC20");
  const sellToken = await SellFactory.deploy("Governance Token", "GOV");
  await sellToken.waitForDeployment();
  const sellTokenAddress = await sellToken.getAddress();
  console.log("SellToken deployed:", sellTokenAddress);

  // === Auction contract ===
  console.log("\n--- Deploying SealedAuction ---");
  const AuctionFactory = await ethers.getContractFactory("SealedAuction");
  const auction = await AuctionFactory.deploy();
  await auction.waitForDeployment();
  const auctionAddress = await auction.getAddress();
  console.log("SealedAuction deployed:", auctionAddress);

  const addresses: Record<string, string> = {
    bidToken: bidTokenAddress,
    sellToken: sellTokenAddress,
    auction: auctionAddress,
  };

  // === Local-only DemoHelper ===
  if (isLocal) {
    console.log("\n--- Deploying DemoHelper (local hardhat only) ---");
    const HelperFactory = await ethers.getContractFactory("DemoHelper");
    const helper = await HelperFactory.deploy(auctionAddress);
    await helper.waitForDeployment();
    const helperAddress = await helper.getAddress();
    console.log("DemoHelper deployed:", helperAddress);
    addresses.demoHelper = helperAddress;
  } else {
    console.log("\nSkipping DemoHelper (testnet/mainnet uses client-side FHE encryption).");
  }

  console.log("\n========================================");
  console.log(`Deployment complete on ${network.name}`);
  console.log("========================================");
  for (const [name, addr] of Object.entries(addresses)) {
    console.log(`${name.padEnd(16)}${addr}`);
  }
  console.log("========================================");

  // Write addresses to frontend
  const frontendDir = path.join(__dirname, "..", "frontend", "src", "contracts");
  if (!fs.existsSync(frontendDir)) fs.mkdirSync(frontendDir, { recursive: true });
  const addressesFile = path.join(frontendDir, "addresses.js");
  const content = `// Auto-generated by deploy script — ${network.name} @ ${new Date().toISOString()}
export const ADDRESSES = ${JSON.stringify(addresses, null, 2)};

export const NETWORK = "${network.name}";
export const CHAIN_ID = ${network.config.chainId};
`;
  fs.writeFileSync(addressesFile, content);
  console.log(`\nAddresses written to ${addressesFile}`);

  // Print verification commands for non-local deployments
  if (!isLocal) {
    console.log("\nVerify contracts on Etherscan:");
    console.log(`  npx hardhat verify --network ${network.name} ${bidTokenAddress}`);
    console.log(`  npx hardhat verify --network ${network.name} ${sellTokenAddress} "Governance Token" "GOV"`);
    console.log(`  npx hardhat verify --network ${network.name} ${auctionAddress}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
